name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout the repository
      
      - name: Set up Python
        uses: actions/setup-python@v2  # Action to set up Python environment
        with:
          python-version: '3.12.3'  # Specify your Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file
      
      - name: Run tests
        run: |
          python -m pytest  # Replace with your test command
      
